title: Temario MI
description: Repositorio del temario MI
theme: just-the-docs

url: https://yrjo.eu/temario

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
